In [1]:
import pandas as pd



df = pd.DataFrame({
    "Student_ID":[101,102,103,104,105,106,107,108,109,110],
    "Name":["Amit","Priya","Rahul","Sneha","Arjun","Kiran","Neha","Ravi","Pooja","Manoj"],
    "Age":[20,21,22,20,23,21,22,20,21,22],
    "Course":["Python","Python","Data Science","Python","Data Science",
              "Python","Data Science","Python","Data Science","Python"],
    "Marks":[85,92,78,88,95,67,81,73,89,90]
})

df.to_csv("students.csv", index=False)

print("students.csv created successfully")

students.csv created successfully

In [2]:
import os

print(os.getcwd())

C:\Users\USER

In [4]:
df=pd.read_csv("students.csv")

In [5]:
df

   Student_ID   Name  Age        Course  Marks
0         101   Amit   20        Python     85
1         102  Priya   21        Python     92
2         103  Rahul   22  Data Science     78
3         104  Sneha   20        Python     88
4         105  Arjun   23  Data Science     95
5         106  Kiran   21        Python     67
6         107   Neha   22  Data Science     81
7         108   Ravi   20        Python     73
8         109  Pooja   21  Data Science     89
9         110  Manoj   22        Python     90

In [6]:
df.head()

   Student_ID   Name  Age        Course  Marks
0         101   Amit   20        Python     85
1         102  Priya   21        Python     92
2         103  Rahul   22  Data Science     78
3         104  Sneha   20        Python     88
4         105  Arjun   23  Data Science     95

In [7]:
df.head(3)

   Student_ID   Name  Age        Course  Marks
0         101   Amit   20        Python     85
1         102  Priya   21        Python     92
2         103  Rahul   22  Data Science     78

In [8]:
df.tail()

   Student_ID   Name  Age        Course  Marks
5         106  Kiran   21        Python     67
6         107   Neha   22  Data Science     81
7         108   Ravi   20        Python     73
8         109  Pooja   21  Data Science     89
9         110  Manoj   22        Python     90

In [9]:
df.tail(2)

   Student_ID   Name  Age        Course  Marks
8         109  Pooja   21  Data Science     89
9         110  Manoj   22        Python     90

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Course      10 non-null     object
 4   Marks       10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

In [11]:
df.describe()

       Student_ID        Age      Marks
count    10.00000  10.000000  10.000000
mean    105.50000  21.200000  83.800000
std       3.02765   1.032796   8.929352
min     101.00000  20.000000  67.000000
25%     103.25000  20.250000  78.750000
50%     105.50000  21.000000  86.500000
75%     107.75000  22.000000  89.750000
max     110.00000  23.000000  95.000000

In [13]:
df['Age']

0    20
1    21
2    22
3    20
4    23
5    21
6    22
7    20
8    21
9    22
Name: Age, dtype: int64

In [14]:
df['Age'].max()

np.int64(23)

In [20]:
df['Age'].min()

np.int64(20)

In [16]:
df['Marks']

np.int64(838)

In [18]:
df['Marks'].mean()

np.float64(83.8)

In [21]:
avg=df['Marks'].mean()

In [22]:
print("Averaghe is:",avg)

Averaghe is: 83.8

In [26]:
df[df['Marks']>90]

   Student_ID   Name  Age        Course  Marks
1         102  Priya   21        Python     92
4         105  Arjun   23  Data Science     95

In [27]:
high_scorers = df[df["Marks"] > 80]
print(high_scorers)

   Student_ID   Name  Age        Course  Marks
0         101   Amit   20        Python     85
1         102  Priya   21        Python     92
3         104  Sneha   20        Python     88
4         105  Arjun   23  Data Science     95
6         107   Neha   22  Data Science     81
8         109  Pooja   21  Data Science     89
9         110  Manoj   22        Python     90

In [30]:
df[df['Course']=='Python']

   Student_ID   Name  Age  Course  Marks
0         101   Amit   20  Python     85
1         102  Priya   21  Python     92
3         104  Sneha   20  Python     88
5         106  Kiran   21  Python     67
7         108   Ravi   20  Python     73
9         110  Manoj   22  Python     90

In [31]:
len(high_scorers)

7

In [32]:
len(df[df['Course']=='Python'])

6

In [36]:
df['Grade']=df['Marks'].apply(
    lambda x:"A" if x>=90 else
             "B" if x>80 else
             "c"
               
    )

In [37]:
df

   Student_ID   Name  Age        Course  Marks Grade
0         101   Amit   20        Python     85     B
1         102  Priya   21        Python     92     A
2         103  Rahul   22  Data Science     78     c
3         104  Sneha   20        Python     88     B
4         105  Arjun   23  Data Science     95     A
5         106  Kiran   21        Python     67     c
6         107   Neha   22  Data Science     81     B
7         108   Ravi   20        Python     73     c
8         109  Pooja   21  Data Science     89     B
9         110  Manoj   22        Python     90     A